version: '3.7'
services:
  app: 
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    image: go-assignment
    container_name: go-assignement
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - api_network

  postgres:
    image: postgres:16
    container_name: postgres-go-assignment
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api_network

volumes:
  pgdata:                                
    name: pgdata

networks:
  api_network:
    driver: bridge